### ISSUE TITLE
Weird double shadow on some GTK3 apps

### ISSUE THREAD

**Issue by hexchain** [chjj/compton#189]
With those GTK3 applications that have their own shadow (and probably window border), if compton's shadow is turned on, those windows will have bigger square box  with shadow surrounding them.

Screenshot with compton shadow on: http://i.imgur.com/AbWHh66.png
compton shadow off: http://i.imgur.com/k0nFnT4.png

I'm using Openbox on Arch Linux.

**Comment by tigamai** [comment]
Had the same problem with gtk3/compton/i3. Using i3 4.8-3, gtk3 3.14.9-1, compton v0.1_beta2-5 on Arch.

This fixed the problem for me:

You need to edit the file ~/.config/gtk-3.0/gtk.css
```css
.window-frame, .window-frame:backdrop {
 box-shadow: 0 0 0 black;
 border-style: none;
 margin: 0;
 border-radius: 0;
}

.titlebar {
 border-radius: 0;
}
```
Source: https://www.reddit.com/r/i3wm/comments/2qk7c3/with_i3_compton_and_gtk3_make_rounded_corners_on/cn6zjme
